qumbia-svg: QuSvgWriter Class Reference
QuSvgWriter Class Reference
QuSvgWriter is a reader that uses QObject to display values.
#include <qusvgwriter.h>
Public Slots
void setTarget (const QString &target)
set the target
void write (const QString &s)
write a string to the target
void write ()
Signals
void newData (const CuData &)
Public Member Functions
QuSvgWriter (QWidget *w, Cumbia *cumbia, const CuControlsWriterFactoryI &r_fac)
Constructor with the parent widget, an engine specific Cumbia implementation and a CuControlsReaderFactoryI interface.
QuSvgWriter (QWidget *w, CumbiaPool *cumbia_pool, const CuControlsFactoryPool &fpool)
Constructor with the parent widget, CumbiaPool and CuControlsFactoryPool
virtual ~QuSvgWriter ()
QString target () const
returns the target of the writer
CuContext * getContext () const
returns a pointer to the CuContext used as a delegate for the connection.
void onUpdate (const CuData &d)
Properties
QString target
Detailed Description
QuSvgWriter is a reader that uses QObject to display values.
Connection is initiated with setSource. When new data arrives, it is displayed and the newData convenience signal is emitted.
getContext returns a pointer to the CuContext used as a delegate for the connection.
Constructor & Destructor Documentation
QuSvgWriter() [1/2]
QuSvgWriter::QuSvgWriter (QWidget * w, Cumbia * cumbia, const CuControlsWriterFactoryI & r_factory)
Constructor with the parent widget, an engine specific Cumbia implementation and a CuControlsReaderFactoryI interface.
Please refer to md_src_cumbia_qtcontrols_widget_constructors documentation.
QuSvgWriter() [2/2]
QuSvgWriter::QuSvgWriter (QWidget * w, CumbiaPool * cumbia_pool, const CuControlsFactoryPool & fpool)
Constructor with the parent widget, CumbiaPool and CuControlsFactoryPool
Please refer to md_src_cumbia_qtcontrols_widget_constructors documentation.
~QuSvgWriter()
QuSvgWriter::~QuSvgWriter () virtual
Member Function Documentation
getContext()
CuContext * QuSvgWriter::getContext () const
returns a pointer to the CuContext used as a delegate for the connection.
returns the pointer to the CuContext
Returns
CuContext
CuContext sets up the connection and is used as a mediator to send and get data to and from the reader.
See also
CuContext
newData
void QuSvgWriter::newData (const CuData &) signal
Referenced by onUpdate().
onUpdate()
void QuSvgWriter::onUpdate (const CuData & d)
References newData().
setTarget
void QuSvgWriter::setTarget (const QString & target) slot
set the target
Connect the reader to the specified source.
Parameters
the name of the target
If a reader with a different source is configured, it is deleted. If options have been set with QuContext::setOptions, they are used to set up the reader as desired.
See also
QuContext::setOptions
source
References target().
target()
QString QuSvgWriter::target () const
returns the target of the writer
Returns
a QString with the name of the target
Referenced by setTarget().
write [1/2]
void QuSvgWriter::write (const QString & s) slot
write a string to the target
Parameters
s the string to be written on the target
write [2/2]
void QuSvgWriter::write () slot
Property Documentation
target
QString QuSvgWriter::target read write
The documentation for this class was generated from the following files:
qusvgwriter.h
qusvgwriter.cpp