qumbia-svg: QuDomElement Class Reference
QuDomElement Class Reference
#include <qudomelement.h>
Public Member Functions
QuDomElement (QuDom *x)
QuDomElement (const QDomElement &dome)
QuDomElement (QuDom *x, const QDomElement &e)
QuDomElement (const QuDomElement &other)
QuDomElement ()
QuDomElement & operator= (const QuDomElement &)
bool isNull () const
QuDomElement operator [] (const QString &id_path)
QuDomElement::operator [] search a QuDomElement with the attribute id matching the given id or id path
QuDomElement operator [] (const std::string &id)
QuDomElement operator [] (const char *id)
QuDomElement operator [] (const QString &id_path) const
QDomElement element () const
Returns the QDomElement referenced by this object.
QString attribute (const QString &a) const
QuDomElement::attribute returns the attribute value corresponding to the attribute name a
void setAttribute (const QString &name, const QString &value)
set the attribute name to value value on this element
QString a (const QString &name) const
QuDomElement::a(const QString &name) is a shortcut for QuDomElement::attribute.
void a (const QString &name, const QString &value)
QuDomElement::a(const QString &name, const QString &value) is a shortcut for QuDomElement::setAttribute.
QuDomElement findById (const QString &id, const QuDomElement &parent) const
QDomElement firstChild (const QString &tagnam) const
Find the first <tagnam> child found.
QDomNodeList children (const QString &tagnam) const
Get the list of child nodes with the given tag name.
QString itemId () const
search from this element up across its parents to find the "item" attribute. Return the id of such item
bool splitAttName (const QString &full, QString &attribute, QString &property)
Get the attribute name and the property name from a attribute/property name.
QString toDeclarationList (QString &name, const QString &value)
From an attribute name like name/sub, get the full attribute value obtained modifying only the sub section of the attribute.
Constructor & Destructor Documentation
QuDomElement() [1/5]
QuDomElement::QuDomElement (QuDom * x)
QuDomElement() [2/5]
QuDomElement::QuDomElement (const QDomElement & dome)
QuDomElement() [3/5]
QuDomElement::QuDomElement (QuDom * x, const QDomElement & e)
QuDomElement() [4/5]
QuDomElement::QuDomElement (const QuDomElement & other)
QuDomElement() [5/5]
QuDomElement::QuDomElement ()
Referenced by findById().
Member Function Documentation
a() [1/2]
QString QuDomElement::a (const QString & name) const
QuDomElement::a(const QString &name) is a shortcut for QuDomElement::attribute.
See also
QuDomElement::attribute
References attribute().
Referenced by attribute(), QuSvgLayerHelper::layerVisible(), QuSvgView::onDocumentLoaded(), QuDom::setItemAttribute(), QuSvgLayerHelper::setLayerVisible(), and toDeclarationList().
a() [2/2]
void QuDomElement::a (const QString & name, const QString & value)
QuDomElement::a(const QString &name, const QString &value) is a shortcut for QuDomElement::setAttribute.
See also
QuDomElement::setAttribute
References setAttribute().
attribute()
QString QuDomElement::attribute (const QString & a) const
QuDomElement::attribute returns the attribute value corresponding to the attribute name a
Parameters
a the attribute name
Returns
the value of the attribute "a"
Note
Calls QDomElement::attribute on the underlying QDomElement
References a().
Referenced by a(), findById(), and splitAttName().
children()
QDomNodeList QuDomElement::children (const QString & tagnam) const
Get the list of child nodes with the given tag name.
Parameters
tagnam the name of the tag
Returns
list of child nodes with the given tag, as QDomNodeList
element()
QDomElement QuDomElement::element () const
Returns the QDomElement referenced by this object.
Returns
The QDomElement referenced by this object
Referenced by QuDom::findById(), operator [](), and QuSvgLayerHelper::setLayerVisible().
findById()
QuDomElement QuDomElement::findById (const QString & id, const QuDomElement & parent) const
References attribute(), QuDom::getDocument(), isNull(), and QuDomElement().
Referenced by QuDom::findById().
firstChild()
QDomElement QuDomElement::firstChild (const QString & tagnam) const
Find the first <tagnam> child found.
Returns
the first <tagnam> QDomElement found, or a null QDomElement
isNull()
bool QuDomElement::isNull () const
Referenced by findById(), QuSvgHelperAppActionProvider::handlesEventType(), QuSvgLayerHelper::layerVisible(), QuSvgView::onDocumentLoaded(), operator [](), QuDom::setItemAttribute(), and QuSvgLayerHelper::setLayerVisible().
itemId()
QString QuDomElement::itemId () const
search from this element up across its parents to find the "item" attribute. Return the id of such item
Returns
the id of the dom element that has the attribute "item"
The search is performed from this element up across its parents
Referenced by QuSvgView::onElementChange().
operator []() [1/4]
QuDomElement QuDomElement::operator [] (const QString & id_path)
QuDomElement::operator [] search a QuDomElement with the attribute id matching the given id or id path
Parameters
id_path A single id or an id path in the form id1/id2/.../idN
Returns
Either a null QuDomElement if the search criteria did not produce a result or the QuDomElement matching the input id or id path.
Observation
If a search path is provided, the child nodes are selected hierarchically and the result is found faster.
Notes
The id matching is performed on this QuDomElement first, before descending into the children
The QuDom id cache is searched first. If the result is a miss, a recursive search is performed on this QuDomElement's children.
See also
QuDom::setCacheElementsOnAccessEnabled
References QuDom::cacheOnAccessEnabled(), element(), and isNull().
Referenced by operator []().
operator []() [2/4]
QuDomElement QuDomElement::operator [] (const std::string & id)
References operator []().
operator []() [3/4]
QuDomElement QuDomElement::operator [] (const char * id)
References operator []().
operator []() [4/4]
QuDomElement QuDomElement::operator [] (const QString & id_path) const
operator=()
QuDomElement & QuDomElement::operator= (const QuDomElement & o)
setAttribute()
void QuDomElement::setAttribute (const QString & name, const QString & value)
set the attribute name to value value on this element
Parameters
name the attribute name
value the value to set
Attribute name
You can access sub properties in a property list attribute, like "style", specifying the sub property name after the attribute name separated by a "/", e.g.
setAttribute("style/fill", "#00ff00");
This will either set the fill property to #00ff00 or add it to the "style" attribute if yet missing.
See also
toDeclarationList
References toDeclarationList().
Referenced by a().
splitAttName()
bool QuDomElement::splitAttName (const QString & full, QString & attribute, QString & property)
Get the attribute name and the property name from a attribute/property name.
Parameters
full the attribute name plus the property selector, e.g. "style/fill"
attribute the attribute name, e.g. "style"
property the property name, e.g. "fill"
Returns
true if the full parameter is a composite name, e.g. "style/fill", false if full does not contain a '/' separator
References attribute().
Referenced by QuSvgReadLink::QuSvgReadLink(), and toDeclarationList().
toDeclarationList()
QString QuDomElement::toDeclarationList (QString & name, const QString & value)
From an attribute name like name/sub, get the full attribute value obtained modifying only the sub section of the attribute.
If the input name does not contain the '/' separator, value is returned without modification. If this element does not have the specified attribute, an empty string is returned.
Parameters
name attribute_name/sub_property: e.g. style/fill or style/stroke After the call, name will contain the attribute name (e.g. style)
value the new value, e.g. #ff0000 (red color)
Returns
The attribute with the property changed within the property list, or an empty string if the element has no attribute with the given name. If the element contains the attribute with name name, but the property does not exist, the property is added to the property list. For example you can add to the style the property stroke-width and set it to 5 calling
toDeclarationList("style/stroke-width", "5");
Example
Before calling the method, a "rect" element has the attribute style="fill:#ccc00f;stroke:#ff0009" Call
toDeclarationList("style/fill", "#ff0000");
returns style="fill:#ff0000;stroke:#ff0009" and name will be "style"
References a(), and splitAttName().
Referenced by setAttribute().
The documentation for this class was generated from the following files:
qudomelement.h
qudomelement.cpp