qumbia-svg: QuSvgView Class Reference
QuSvgView Class Reference
#include <qusvgview.h>
Public Types
enum RendererType { Native, OpenGL, Image }
Public Slots
void setHighQualityAntialiasing (bool highQualityAntialiasing)
void zoomIn ()
void zoomOut ()
void resetZoom ()
void onItemClicked (QuGraphicsSvgItem *item, const QPointF &scenePos, const QPointF &pos)
void onItemContextMenuRequest (QuGraphicsSvgItem *item, const QPointF &scenePos, const QPointF &pos)
Signals
void zoomChanged ()
void itemClicked (QuGraphicsSvgItem *item, const QPointF &scenePos, const QPointF &pos)
void itemContextMenuRequest (QuGraphicsSvgItem *item, const QPointF &scenePos, const QPointF &pos)
Public Member Functions
QuSvgView (QWidget *parent=nullptr)
void setRenderer (RendererType type=Native)
void drawBackground (QPainter *p, const QRectF &rect) override
QSize svgSize () const
QSvgRenderer * renderer () const
qreal zoomFactor () const
void onDocumentLoaded (QuDom *dom, const QStringList &ids)
void onElementChange (const QString &id, QuDomElement *dom_e)
Protected Slots
void sceneChanged (const QList< QRectF > &rects)
Protected Member Functions
void wheelEvent (QWheelEvent *event) override
void paintEvent (QPaintEvent *event) override
Member Enumeration Documentation
RendererType
enum QuSvgView::RendererType
Enumerator
Native
OpenGL
Image
Constructor & Destructor Documentation
QuSvgView()
QuSvgView::QuSvgView (QWidget * parent = nullptr) explicit
References Native.
Member Function Documentation
drawBackground()
void QuSvgView::drawBackground (QPainter * p, const QRectF & rect) override
itemClicked
void QuSvgView::itemClicked (QuGraphicsSvgItem * item, const QPointF & scenePos, const QPointF & pos) signal
Referenced by onItemClicked().
itemContextMenuRequest
void QuSvgView::itemContextMenuRequest (QuGraphicsSvgItem * item, const QPointF & scenePos, const QPointF & pos) signal
Referenced by onItemContextMenuRequest().
onDocumentLoaded()
void QuSvgView::onDocumentLoaded (QuDom * dom, const QStringList & ids) virtual
Implements QuDomListener.
References QuDomElement::a(), QuDom::getDocument(), QuDomElement::isNull(), onItemClicked(), onItemContextMenuRequest(), and renderer().
onElementChange()
void QuSvgView::onElementChange (const QString & id, QuDomElement * dom_e) virtual
Implements QuDomListener.
References QuDomElement::itemId(), and renderer().
onItemClicked
void QuSvgView::onItemClicked (QuGraphicsSvgItem * item, const QPointF & scenePos, const QPointF & pos) slot
References itemClicked().
Referenced by onDocumentLoaded().
onItemContextMenuRequest
void QuSvgView::onItemContextMenuRequest (QuGraphicsSvgItem * item, const QPointF & scenePos, const QPointF & pos) slot
References itemContextMenuRequest().
Referenced by onDocumentLoaded().
paintEvent()
void QuSvgView::paintEvent (QPaintEvent * event) override protected
References Image.
renderer()
QSvgRenderer * QuSvgView::renderer () const
Referenced by onDocumentLoaded(), and onElementChange().
resetZoom
void QuSvgView::resetZoom () slot
References zoomChanged(), and zoomFactor().
sceneChanged
void QuSvgView::sceneChanged (const QList< QRectF > & rects) protected slot
setHighQualityAntialiasing
void QuSvgView::setHighQualityAntialiasing (bool highQualityAntialiasing) slot
setRenderer()
void QuSvgView::setRenderer (RendererType type = Native)
References OpenGL.
svgSize()
QSize QuSvgView::svgSize () const
wheelEvent()
void QuSvgView::wheelEvent (QWheelEvent * event) override protected
zoomChanged
void QuSvgView::zoomChanged () signal
Referenced by resetZoom().
zoomFactor()
qreal QuSvgView::zoomFactor () const
Referenced by resetZoom().
zoomIn
void QuSvgView::zoomIn () slot
zoomOut
void QuSvgView::zoomOut () slot
The documentation for this class was generated from the following files:
qusvgview.h
qusvgview.cpp