qumbia-svg: QuSvgReader Class Reference
QuSvgReader Class Reference
QuSvgReader is a reader used by the cumbia-svg module.
#include <qusvgreader.h>
Public Member Functions
QuSvgReader (Cumbia *cumbia, const CuControlsReaderFactoryI &r_fac)
Constructor with the parent widget, an engine specific Cumbia implementation and a CuControlsReaderFactoryI interface.
QuSvgReader (CumbiaPool *cumbia_pool, const CuControlsFactoryPool &fpool)
Constructor with the parent widget, CumbiaPool and CuControlsFactoryPool
virtual ~QuSvgReader ()
QString source () const
returns the source of the reader
CuContext * getContext () const
returns a pointer to the CuContext used as a delegate for the connection.
void setSource (const QString &s)
set the source and start reading
void unsetSource ()
disconnect the source
int addLink (const QuSvgReadLink &link)
int removeLink (const QuSvgReadLink &link)
const QVector< QuSvgReadLink > & links () const
void deactivate (const QString &id)
void reactivate (const QString &id)
int inactiveCount () const
void setLinkInactive (const QString &link_id, bool inactive)
void addListener (QuSvgConnectionListener *dl)
void removeListener (QuSvgConnectionListener *dl)
void setOptions (const QMap< QString, QString > &options)
Set options on the reader.
QString rawSrc () const
void onUpdate (const CuData &d)
Detailed Description
QuSvgReader is a reader used by the cumbia-svg module.
Connection is initiated with setSource. When new data is ready, it can be manipulated before changing properties in the DOM.
getContext returns a pointer to the CuContext used as a delegate for the connection.
Constructor & Destructor Documentation
QuSvgReader() [1/2]
QuSvgReader::QuSvgReader (Cumbia * cumbia, const CuControlsReaderFactoryI & r_factory)
Constructor with the parent widget, an engine specific Cumbia implementation and a CuControlsReaderFactoryI interface.
Please refer to md_src_cumbia_qtcontrols_widget_constructors documentation.
QuSvgReader() [2/2]
QuSvgReader::QuSvgReader (CumbiaPool * cumbia_pool, const CuControlsFactoryPool & fpool)
Constructor with the parent widget, CumbiaPool and CuControlsFactoryPool
Please refer to md_src_cumbia_qtcontrols_widget_constructors documentation.
~QuSvgReader()
QuSvgReader::~QuSvgReader () virtual
Member Function Documentation
addLink()
int QuSvgReader::addLink (const QuSvgReadLink & link)
References QuSvgReadLink::id, and reactivate().
Referenced by QuSvgConnectionsPool::add_link().
addListener()
void QuSvgReader::addListener (QuSvgConnectionListener * dl)
Referenced by QuSvgConnectionsPool::add_link().
deactivate()
void QuSvgReader::deactivate (const QString & id)
References inactiveCount(), and setLinkInactive().
Referenced by QuSvgConnectionsPool::activateSources(), and removeLink().
getContext()
CuContext * QuSvgReader::getContext () const
returns a pointer to the CuContext used as a delegate for the connection.
returns the pointer to the CuContext
Returns
CuContext
CuContext sets up the connection and is used as a mediator to send and get data to and from the reader.
See also
CuContext
inactiveCount()
int QuSvgReader::inactiveCount () const
References QuSvgReadLink::inactive.
Referenced by deactivate().
links()
const QVector< QuSvgReadLink > & QuSvgReader::links () const
Referenced by QuSvgConnectionsPool::activateSources(), and QuSvgConnectionsPool::findReaderById().
onUpdate()
void QuSvgReader::onUpdate (const CuData & d)
References QuSvgConnectionListener::onUpdate().
rawSrc()
QString QuSvgReader::rawSrc () const
reactivate()
void QuSvgReader::reactivate (const QString & id)
References setLinkInactive().
Referenced by QuSvgConnectionsPool::activateSources(), and addLink().
removeLink()
int QuSvgReader::removeLink (const QuSvgReadLink & link)
References deactivate(), and QuSvgReadLink::id.
removeListener()
void QuSvgReader::removeListener (QuSvgConnectionListener * dl)
setLinkInactive()
void QuSvgReader::setLinkInactive (const QString & link_id, bool inactive)
Referenced by deactivate(), and reactivate().
setOptions()
void QuSvgReader::setOptions (const QMap< QString, QString > & options)
Set options on the reader.
Parameters
options a map of option-names - option-values to set on the CuContext
The method tries to convert the values into bool (if value is either "true" or "false"), integer (if no '.' or 'e' characters are found) or double. If conversion to numbers fails, the option is set as std::string
Referenced by QuSvgConnectionsPool::add_link().
setSource()
void QuSvgReader::setSource (const QString & s)
set the source and start reading
Connect the reader to the specified source.
Parameters
the name of the source
If a reader with a different source is configured, it is deleted. If options have been set with QuContext::setOptions, they are used to set up the reader as desired.
See also
QuContext::setOptions
source
Referenced by QuSvgConnectionsPool::add_link().
source()
QString QuSvgReader::source () const
returns the source of the reader
Returns
a QString with the name of the source
unsetSource()
void QuSvgReader::unsetSource ()
disconnect the source
remove the source and stop reading
The documentation for this class was generated from the following files:
qusvgreader.h
qusvgreader.cpp