qumbia-svg: QuSvgReadersPool Class Reference
QuSvgReadersPool Class Reference
#include <qusvgreaderspool.h>
Public Slots
void activateSources (const QStringList &ids, bool activate)
Public Member Functions
QuSvgReadersPool (Cumbia *cumbia, const CuControlsReaderFactoryI &r_fac, QObject *parent)
QuSvgReadersPool (CumbiaPool *cumbia_pool, const CuControlsFactoryPool &fpool, QObject *parent=nullptr)
void setup_links (const QList< QuSvgLink > &links, QuSvgReaderListener *l)
void add_link (const QuSvgLink &link, QuSvgReaderListener *l)
Constructor & Destructor Documentation
QuSvgReadersPool() [1/2]
QuSvgReadersPool::QuSvgReadersPool (Cumbia * cumbia, const CuControlsReaderFactoryI & r_fac, QObject * parent)
QuSvgReadersPool() [2/2]
QuSvgReadersPool::QuSvgReadersPool (CumbiaPool * cumbia_pool, const CuControlsFactoryPool & fpool, QObject * parent = nullptr)
Member Function Documentation
activateSources
void QuSvgReadersPool::activateSources (const QStringList & ids, bool activate) slot
References QuSvgReader::deactivate(), QuSvgLink::id, QuSvgReader::links(), and QuSvgReader::reactivate().
add_link()
void QuSvgReadersPool::add_link (const QuSvgLink & link, QuSvgReaderListener * l)
References QuSvgReader::addLink(), QuSvgReader::addListener(), QuSvgLink::options, QuSvgReader::setOptions(), QuSvgReader::setSource(), and QuSvgLink::src.
Referenced by setup_links().
setup_links()
void QuSvgReadersPool::setup_links (const QList< QuSvgLink > & links, QuSvgReaderListener * l)
References add_link().
The documentation for this class was generated from the following files:
qusvgreaderspool.h
qusvgreaderspool.cpp