qumbia-svg: QuSvgWriteHandler Class Reference
QuSvgWriteHandler Class Reference
#include <qusvgwritehandler.h>
Public Slots
void exec_dialog ()
void processItemClicked (QuGraphicsSvgItem *it, const QPointF &scenePos, const QPointF &pos)
void processOnItemContextMenuRequest (QuGraphicsSvgItem *it, const QPointF &scenePos, const QPointF &pos)
Public Member Functions
QuSvgWriteHandler (QuSvgView *view, const QuDom &dom, CumbiaPool *cu_pool, const CuControlsFactoryPool &f_pool)
QuSvgWriteHandler (QuSvgView *view, const QuDom &dom, Cumbia *cu, const CuControlsReaderFactoryI &rf, const CuControlsWriterFactoryI &wf)
~QuSvgWriteHandler ()
Constructor & Destructor Documentation
QuSvgWriteHandler() [1/2]
QuSvgWriteHandler::QuSvgWriteHandler (QuSvgView * view, const QuDom & dom, CumbiaPool * cu_pool, const CuControlsFactoryPool & f_pool)
References processItemClicked(), and processOnItemContextMenuRequest().
QuSvgWriteHandler() [2/2]
QuSvgWriteHandler::QuSvgWriteHandler (QuSvgView * view, const QuDom & dom, Cumbia * cu, const CuControlsReaderFactoryI & rf, const CuControlsWriterFactoryI & wf)
~QuSvgWriteHandler()
QuSvgWriteHandler::~QuSvgWriteHandler ()
Member Function Documentation
exec_dialog
void QuSvgWriteHandler::exec_dialog () slot
Referenced by processOnItemContextMenuRequest().
processItemClicked
void QuSvgWriteHandler::processItemClicked (QuGraphicsSvgItem * it, const QPointF & scenePos, const QPointF & pos) slot
Referenced by QuSvgWriteHandler().
processOnItemContextMenuRequest
void QuSvgWriteHandler::processOnItemContextMenuRequest (QuGraphicsSvgItem * it, const QPointF & scenePos, const QPointF & pos) slot
References exec_dialog().
Referenced by QuSvgWriteHandler().
The documentation for this class was generated from the following files:
qusvgwritehandler.h
qusvgwritehandler.cpp