qumbia-svg: QuDom Class Reference
QuDom Class Reference
The QuDom class loads and represents the DOM of the svg source.
#include <qudom.h>
Public Member Functions
QuDom ()
QuDom (const QuDom &other)
virtual ~QuDom ()
QuDom & operator= (const QuDom &)
QDomDocument getDocument () const
bool setContent (const QByteArray &svg)
Populate the DOM with the content in svg
QString getAttribute (const QDomElement &el, const QString &attribute)
QDomElement findById (const QString &id, const QDomElement &parent) const
returns the QDomElement with the given id, searched under parent
QDomElement operator[] (const char *id)
QuDom::operator [] returns the QDomElement with the given id or a null QDomElement if the svg does not contain an element with the given id.
const QDomElement operator[] (const char *id) const
QDomElement operator[] (const QString &id)
const QDomElement operator[] (const QString &) const
QDomElement operator[] (const std::string &id)
const QDomElement operator[] (const std::string &) const
void parse (const QDomNode &parent) const
bool setItemAttribute (const QString &id, const QString &attnam, const QString &attval)
QString itemAttribute (const QString &id, const QString &attnam)
bool setItemText (const QString &id, const QString &text)
QString itemText (const QString &id) const
bool tagMatch (const QString &tag, const QString &other) const
void addDomListener (QuDomListener *l)
QList< QuDomListener * > getDomListeners () const
QList< QuSvgReadLink > takeReadLinkDefs () const
bool hasLinks () const
Returns true if the dom contains *<read>* nodes.
QString readerTagName () const
QString error () const
void setCacheOnAccessEnabled (bool enabled)
bool cacheOnAccessEnabled () const
Friends
class QuDomElement
Detailed Description
The QuDom class loads and represents the DOM of the svg source.
Create the DOM calling setContent. This is usually accomplished either by the QuSvg::loadFile or QuSvg::loadSvg methods.
A QDomElement can be searched with the findById method or using the overloaded operator [] that takes a string as argument and returns the QDomElement with the specified id attribute or a null QDomElement if there is no match.
Constructor & Destructor Documentation
QuDom() [1/2]
QuDom::QuDom ()
QuDom() [2/2]
QuDom::QuDom (const QuDom & other)
~QuDom()
QuDom::~QuDom () virtual
Member Function Documentation
addDomListener()
void QuDom::addDomListener (QuDomListener * l)
cacheOnAccessEnabled()
bool QuDom::cacheOnAccessEnabled () const
Referenced by QuDomElement::operator []().
error()
QString QuDom::error () const
findById()
QDomElement QuDom::findById (const QString & id, const QDomElement & parent) const
returns the QDomElement with the given id, searched under parent
Parameters
id the id to search for
parent the parent node
Returns
the found QDomElement or an empty QDomElement
Important observation
Please consider using QuDomElement::operator [] if you want to perform a faster search when a id search path can be provided.
Example:
QuDomElement root_de(this);
QuDomElement e = root_de["layer1/rectangle"];
if(!e.isNull())
     // found!
QuDomElement::operator [] first performs a search on the cache.
Notes
Elements with the item attribute set to any value different from "false" are stored in a cache by default. Those represent nodes in the svg tree that are directly mapped into QGraphicsSvgItem items in the QuSvgView. If cacheElementsOnAccessEnabled is true, all other QDomElement are cached when they are found by this method, so that subsequent searches can hit the cache and be faster. If cacheElementsOnAccessEnabled is false, only elements with the item attribute not set to false remain cached, and every other search is done recursively traversing the tree.
References QuDomElement::element(), and QuDomElement::findById().
Referenced by operator[](), setItemAttribute(), and setItemText().
getAttribute()
QString QuDom::getAttribute (const QDomElement & el, const QString & attribute)
getDocument()
QDomDocument QuDom::getDocument () const
Referenced by QuDomElement::findById(), QuSvgView::onDocumentLoaded(), setItemAttribute(), and setItemText().
getDomListeners()
QList< QuDomListener * > QuDom::getDomListeners () const
hasLinks()
bool QuDom::hasLinks () const
Returns true if the dom contains *<read>* nodes.
Returns
true if the DOM contains *<read>* nodes, false otherwise.
itemAttribute()
QString QuDom::itemAttribute (const QString & id, const QString & attnam)
itemText()
QString QuDom::itemText (const QString & id) const
operator=()
QuDom & QuDom::operator= (const QuDom & other)
operator[]() [1/6]
QDomElement QuDom::operator[] (const char * id)
QuDom::operator [] returns the QDomElement with the given id or a null QDomElement if the svg does not contain an element with the given id.
Parameters
id the id to search across the svg document
Returns
the QDomElement with the given id or a null QDomElement
This is a convenience method for findById. It is equivalent to
findById(id, getDocument().firstChildElement());
See also
findById
References findById().
operator[]() [2/6]
const QDomElement QuDom::operator[] (const char * id) const
References findById().
operator[]() [3/6]
QDomElement QuDom::operator[] (const QString & id)
operator[]() [4/6]
const QDomElement QuDom::operator[] (const QString & id) const
operator[]() [5/6]
QDomElement QuDom::operator[] (const std::string & id)
operator[]() [6/6]
const QDomElement QuDom::operator[] (const std::string & id) const
parse()
void QuDom::parse (const QDomNode & parent) const
References QuSvgReadLink::isValid(), QuSvgReadLink::message(), and readerTagName().
Referenced by setContent().
readerTagName()
QString QuDom::readerTagName () const
Referenced by parse().
setCacheOnAccessEnabled()
void QuDom::setCacheOnAccessEnabled (bool enabled)
setContent()
bool QuDom::setContent (const QByteArray & svg)
Populate the DOM with the content in svg
Parameters
svg the svg source document as QByteArray
Returns
true if successful, false otherwise
If the method fails, the error message is available through the QuDom::error call.
Cache is cleared before loading the document, so that multiple calls to setContent are possible on the same object.
References QuDomListener::onDocumentLoaded(), and parse().
setItemAttribute()
bool QuDom::setItemAttribute (const QString & id, const QString & attnam, const QString & attval)
References QuDomElement::a(), findById(), getDocument(), QuDomElement::isNull(), and QuDomElement.
setItemText()
bool QuDom::setItemText (const QString & id, const QString & text)
References findById(), and getDocument().
tagMatch()
bool QuDom::tagMatch (const QString & tag, const QString & other) const
Referenced by QuSvgResultDataInterpreter::interpret().
takeReadLinkDefs()
QList< QuSvgReadLink > QuDom::takeReadLinkDefs () const
Friends And Related Function Documentation
QuDomElement
friend class QuDomElement friend
Referenced by setItemAttribute().
The documentation for this class was generated from the following files:
qudom.h
qudom.cpp