qumbia-svg: QuSvgItemEventHandler Class Reference
QuSvgItemEventHandler Class Reference
#include <qusvgitemeventhandler.h>
Public Slots
void processItemClicked (QuGraphicsSvgItem *it)
void processOnItemContextMenuRequest (QuGraphicsSvgItem *it)
Signals
void error (const QString &origin, const QString &message)
Public Member Functions
QuSvgItemEventHandler (QuSvgView *view)
~QuSvgItemEventHandler ()
void addActionProvider (QuSvgActionProviderInterface *ap)
Constructor & Destructor Documentation
QuSvgItemEventHandler()
QuSvgItemEventHandler::QuSvgItemEventHandler (QuSvgView * view) explicit
References processItemClicked(), and processOnItemContextMenuRequest().
~QuSvgItemEventHandler()
QuSvgItemEventHandler::~QuSvgItemEventHandler ()
Member Function Documentation
addActionProvider()
void QuSvgItemEventHandler::addActionProvider (QuSvgActionProviderInterface * ap)
error
void QuSvgItemEventHandler::error (const QString & origin, const QString & message) signal
Referenced by processItemClicked().
processItemClicked
void QuSvgItemEventHandler::processItemClicked (QuGraphicsSvgItem * it) slot
References QuSvgActionProviderInterface::ClickEvent, error(), QuSvgActionProviderInterface::handlesEventType(), QuSvgActionProviderInterface::hasError(), QuSvgActionProviderInterface::message(), QuSvgActionProviderInterface::name(), and QuSvgActionProviderInterface::onClicked().
Referenced by QuSvgItemEventHandler().
processOnItemContextMenuRequest
void QuSvgItemEventHandler::processOnItemContextMenuRequest (QuGraphicsSvgItem * it) slot
References QuSvgActionProviderInterface::ContextualEvent, QuSvgActionProviderInterface::getActionNames(), and QuSvgActionProviderInterface::handlesEventType().
Referenced by QuSvgItemEventHandler().
The documentation for this class was generated from the following files:
qusvgitemeventhandler.h
qusvgitemeventhandler.cpp