qumbia-svg: QuSvgConnectionsPool Class Reference
QuSvgConnectionsPool Class Reference
#include <qusvgconnectionspool.h>
Public Slots
void activateSources (const QStringList &ids, bool activate)
Public Member Functions
QuSvgConnectionsPool (QObject *parent=nullptr)
void init (Cumbia *cumbia, const CuControlsReaderFactoryI &r_fac, const CuControlsWriterFactoryI &w_fac)
void init (CumbiaPool *cumbia_pool, const CuControlsFactoryPool &fpool)
void setup_links (const QList< QuSvgReadLink > &links, QuSvgConnectionListener *l)
void add_link (const QuSvgReadLink &link, QuSvgConnectionListener *l)
QuSvgReader * findReaderById (const QString &id) const
Constructor & Destructor Documentation
QuSvgConnectionsPool()
QuSvgConnectionsPool::QuSvgConnectionsPool (QObject * parent = nullptr)
Member Function Documentation
activateSources
void QuSvgConnectionsPool::activateSources (const QStringList & ids, bool activate) slot
References QuSvgReader::deactivate(), QuSvgReadLink::id, QuSvgReader::links(), and QuSvgReader::reactivate().
add_link()
void QuSvgConnectionsPool::add_link (const QuSvgReadLink & link, QuSvgConnectionListener * l)
References QuSvgReader::addLink(), QuSvgReader::addListener(), QuSvgReadLink::options, QuSvgReader::setOptions(), QuSvgReader::setSource(), and QuSvgReadLink::src.
Referenced by setup_links().
findReaderById()
QuSvgReader * QuSvgConnectionsPool::findReaderById (const QString & id) const
References QuSvgReadLink::id, and QuSvgReader::links().
init() [1/2]
void QuSvgConnectionsPool::init (Cumbia * cumbia, const CuControlsReaderFactoryI & r_fac, const CuControlsWriterFactoryI & w_fac)
init() [2/2]
void QuSvgConnectionsPool::init (CumbiaPool * cumbia_pool, const CuControlsFactoryPool & fpool)
setup_links()
void QuSvgConnectionsPool::setup_links (const QList< QuSvgReadLink > & links, QuSvgConnectionListener * l)
References add_link().
The documentation for this class was generated from the following files:
qusvgconnectionspool.h
qusvgconnectionspool.cpp