qumbia-svg: QuGraphicsSvgItem Class Reference
QuGraphicsSvgItem Class Reference
#include <qugraphicssvgitem.h>
Public Types
enum Shape {
Undefined, ShapeText, ShapeRect, ShapeEllipse,
ShapePath
}
Public Slots
void setClickable (const QString &c)
void setShape (const QString &s)
set the shape of the item, from the svg tag name
Signals
void clicked (QuGraphicsSvgItem *item, const QPointF &scenePos, const QPointF &pos)
void contextMenuRequest (QuGraphicsSvgItem *item, const QPointF &scenePos, const QPointF &pos)
Public Member Functions
QuGraphicsSvgItem ()
bool clickable () const
Shape getShape () const
Get the name of the shape of this item.
Protected Member Functions
void mousePressEvent (QGraphicsSceneMouseEvent *event)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
void contextMenuEvent (QGraphicsSceneContextMenuEvent *e)
void hoverEnterEvent (QGraphicsSceneHoverEvent *e)
void hoverLeaveEvent (QGraphicsSceneHoverEvent *e)
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
Properties
QString clickable
QString shape
Member Enumeration Documentation
Shape
enum QuGraphicsSvgItem::Shape
Enumerator
Undefined
ShapeText
ShapeRect
ShapeEllipse
ShapePath
Constructor & Destructor Documentation
QuGraphicsSvgItem()
QuGraphicsSvgItem::QuGraphicsSvgItem ()
References Undefined.
Member Function Documentation
clickable()
bool QuGraphicsSvgItem::clickable () const
clicked
void QuGraphicsSvgItem::clicked (QuGraphicsSvgItem * item, const QPointF & scenePos, const QPointF & pos) signal
Referenced by mouseReleaseEvent().
contextMenuEvent()
void QuGraphicsSvgItem::contextMenuEvent (QGraphicsSceneContextMenuEvent * e) protected
References contextMenuRequest().
contextMenuRequest
void QuGraphicsSvgItem::contextMenuRequest (QuGraphicsSvgItem * item, const QPointF & scenePos, const QPointF & pos) signal
Referenced by contextMenuEvent().
getShape()
QuGraphicsSvgItem::Shape QuGraphicsSvgItem::getShape () const
Get the name of the shape of this item.
Returns
the name of the shape set with setShape
hoverEnterEvent()
void QuGraphicsSvgItem::hoverEnterEvent (QGraphicsSceneHoverEvent * e) protected
hoverLeaveEvent()
void QuGraphicsSvgItem::hoverLeaveEvent (QGraphicsSceneHoverEvent * e) protected
mousePressEvent()
void QuGraphicsSvgItem::mousePressEvent (QGraphicsSceneMouseEvent * event) protected
mouseReleaseEvent()
void QuGraphicsSvgItem::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) protected
References clicked().
paint()
void QuGraphicsSvgItem::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget) protected
References ShapeEllipse, ShapePath, and ShapeRect.
setClickable
void QuGraphicsSvgItem::setClickable (const QString & c) slot
References ShapeRect, and Undefined.
setShape
void QuGraphicsSvgItem::setShape (const QString & s) slot
set the shape of the item, from the svg tag name
Parameters
s the shape as string (e.g. text, rect, ellipse)
References ShapeEllipse, ShapePath, ShapeRect, ShapeText, and Undefined.
Property Documentation
clickable
bool QuGraphicsSvgItem::clickable write
shape
QString QuGraphicsSvgItem::shape write
The documentation for this class was generated from the following files:
qugraphicssvgitem.h
qugraphicssvgitem.cpp