qumbia-svg: QuSvgActionProviderInterface Class Reference
QuSvgActionProviderInterface Class Reference abstract
#include <qusvgitemeventhandler.h>
Public Types
enum EventType { ClickEvent, ContextualEvent }
Public Member Functions
virtual QStringList getActionNames (QuGraphicsSvgItem *it) const =0
virtual bool onClicked (QuGraphicsSvgItem *it)=0
virtual bool onContextAction (QuGraphicsSvgItem *it, const QString &action_name=QString())=0
virtual bool handlesEventType (QuGraphicsSvgItem *it, EventType et) const =0
virtual QString message () const =0
virtual bool hasError () const =0
virtual QString name () const =0
Member Enumeration Documentation
EventType
enum QuSvgActionProviderInterface::EventType
Enumerator
ClickEvent
ContextualEvent
Member Function Documentation
getActionNames()
virtual QStringList QuSvgActionProviderInterface::getActionNames (QuGraphicsSvgItem * it) const pure virtual
Implemented in QuSvgWriteActionProvider, and QuSvgHelperAppActionProvider.
Referenced by QuSvgItemEventHandler::processOnItemContextMenuRequest().
handlesEventType()
virtual bool QuSvgActionProviderInterface::handlesEventType (QuGraphicsSvgItem * it, EventType et) const pure virtual
Implemented in QuSvgWriteActionProvider, and QuSvgHelperAppActionProvider.
Referenced by QuSvgItemEventHandler::processItemClicked(), and QuSvgItemEventHandler::processOnItemContextMenuRequest().
hasError()
virtual bool QuSvgActionProviderInterface::hasError () const pure virtual
Implemented in QuSvgWriteActionProvider, and QuSvgHelperAppActionProvider.
Referenced by QuSvgItemEventHandler::processItemClicked().
message()
virtual QString QuSvgActionProviderInterface::message () const pure virtual
Implemented in QuSvgWriteActionProvider, and QuSvgHelperAppActionProvider.
Referenced by QuSvgItemEventHandler::processItemClicked().
name()
virtual QString QuSvgActionProviderInterface::name () const pure virtual
Implemented in QuSvgWriteActionProvider, and QuSvgHelperAppActionProvider.
Referenced by QuSvgItemEventHandler::processItemClicked().
onClicked()
virtual bool QuSvgActionProviderInterface::onClicked (QuGraphicsSvgItem * it) pure virtual
Implemented in QuSvgWriteActionProvider, and QuSvgHelperAppActionProvider.
Referenced by QuSvgItemEventHandler::processItemClicked().
onContextAction()
virtual bool QuSvgActionProviderInterface::onContextAction (QuGraphicsSvgItem * it, const QString & action_name = QString()) pure virtual
Implemented in QuSvgWriteActionProvider, and QuSvgHelperAppActionProvider.
The documentation for this class was generated from the following file:
qusvgitemeventhandler.h