qumbia-svg: QuSvg Class Reference
QuSvg Class Reference
#include <qusvg.h>
Public Member Functions
QuSvg (QuDomListener *domlis)
virtual ~QuSvg ()
QuDom * quDom () const
bool loadFile (const QString &fileName)
bool loadSvg (const QByteArray &svg)
QString message () const
bool hasError () const
void init (CumbiaPool *cupool, const CuControlsFactoryPool &fpool)
void init (Cumbia *cumbia, const CuControlsReaderFactoryI &r_fac, const CuControlsWriterFactoryI &w_fac)
void addDataListener (QuSvgDataListener *l)
Add an observer for new data events.
void addDataListener (const QString &id, QuSvgDataListener *l)
associate the given listener to the specified id
void removeDataListener (QuSvgDataListener *l)
Remove the given observer from the list of data listeners.
void removeDataListeners (const QString &id)
removes all listeners associated to id
QuSvgConnectionsPool * getConnectionsPool () const
get a reference to a QuSvgConnectionsPool
void onUpdate (const QuSvgResultData &rd)
Constructor & Destructor Documentation
QuSvg()
QuSvg::QuSvg (QuDomListener * domlis)
~QuSvg()
QuSvg::~QuSvg () virtual
Member Function Documentation
addDataListener() [1/2]
void QuSvg::addDataListener (QuSvgDataListener * l)
Add an observer for new data events.
Parameters
l QuSvgDataListener implementation
See also
removeDataListener
addDataListener() [2/2]
void QuSvg::addDataListener (const QString & id, QuSvgDataListener * l)
associate the given listener to the specified id
Parameters
id the id attribute
l the data listener
Note
l will receive updates only for that specific id.
getConnectionsPool()
QuSvgConnectionsPool * QuSvg::getConnectionsPool () const
get a reference to a QuSvgConnectionsPool
Returns
a pointer to the QuSvgConnectionsPool in use
hasError()
bool QuSvg::hasError () const
init() [1/2]
void QuSvg::init (CumbiaPool * cupool, const CuControlsFactoryPool & fpool)
init() [2/2]
void QuSvg::init (Cumbia * cumbia, const CuControlsReaderFactoryI & r_fac, const CuControlsWriterFactoryI & w_fac)
loadFile()
bool QuSvg::loadFile (const QString & fileName)
References loadSvg().
loadSvg()
bool QuSvg::loadSvg (const QByteArray & svg)
Referenced by loadFile().
message()
QString QuSvg::message () const
onUpdate()
void QuSvg::onUpdate (const QuSvgResultData & rd) virtual
Implements QuSvgConnectionListener.
References QuSvgReadLink::attribute, QuSvgResultData::full_attribute(), QuSvgReadLink::id, QuSvgResultDataInterpreter::interpret(), QuSvgResultData::link, QuSvgDataListener::onError(), QuSvgDataListener::onUpdate(), QuSvgReadLink::src, and QuSvgReadLink::tag_name.
quDom()
QuDom * QuSvg::quDom () const
removeDataListener()
void QuSvg::removeDataListener (QuSvgDataListener * l)
Remove the given observer from the list of data listeners.
Parameters
l QuSvgDataListener to remove
See also
addDataListener
removeDataListeners()
void QuSvg::removeDataListeners (const QString & id)
removes all listeners associated to id
Parameters
id the element with id id
Note
calling removeDataListener with an empty string causes all listeners previously added with QuSvg::addDataListener(QuSvgDataListener *l) to be removed at once.
The documentation for this class was generated from the following files:
qusvg.h
qusvg.cpp